### ISSUE TITLE
thingspeak Server

### ISSUE THREAD

**Issue by kloppy1984** [Zentris/erdfeuchtemessung#11]
Hallo, 
beim Kompelieren, kommt dieser Fehler:

privats.h:68: error: invalid conversion from 'const char*' to 'unsigned int' [-fpermissive]

 tsData thingSpeakServer[] = { (tsData) {"api.thingspeak.com", "184.106.153.149", "DW45DFG525GBT25T", "01"}

Das ist natürlich nur der ausgedachte Key, der da steht
Ich finde den Fehler einfach nicht
ich wäre um ein Hinweis dankbar.

Gruß

**Comment by Zentris** [comment]
Hallo,
die Zeile so, wie du sie geschrieben hast, ist unvollständig...:

```
tsData thingSpeakServer[] = { (tsData) {"api.thingspeak.com", "184.106.153.149", "<our API key>", "<our 1. field number>"}   };
```

Es muss noch die schließende "geschweifte Klammer" => "}" und das abschließende Semikolon dran...
(oder hast du das in deiner Meldung nur vergessen beizugeben??)
