### ISSUE TITLE
Any idea why I might be getting this error during compilation?

### ISSUE THREAD

**Issue by theopensourcerer** [Zentris/erdfeuchtemessung#6]
I am very interested in your code to make the ESP into a frequency counter ;-)

I have compiled a few sketches before but I don;t really understand this. "sensors" is not defined outside of any of these functions...

"/home/alanlord/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++" -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ "-I/home/alanlord/bin/arduino-1.6.12/hardware/esp8266com/esp8266/tools/sdk/include" "-I/home/alanlord/bin/arduino-1.6.12/hardware/esp8266com/esp8266/tools/sdk/lwip/include" "-I/home/alanlord/bin/arduino-1.6.12/hardware/esp8266com/esp8266/tools/sdk/libc/xtensa-lx106-elf/include" "-I/tmp/arduino_build_96324/core" -c -w -Os -g -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -falign-functions=4 -std=c++11 -MMD -ffunction-sections -fdata-sections -DF_CPU=80000000L -DLWIP_OPEN_SRC   -DARDUINO=10612 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DARDUINO_BOARD="ESP8266_ESP01"  -DESP8266 "-I/home/alanlord/bin/arduino-1.6.12/hardware/esp8266com/esp8266/cores/esp8266" "-I/home/alanlord/bin/arduino-1.6.12/hardware/esp8266com/esp8266/variants/generic" "-I/home/alanlord/Arduino/libraries/Streaming" "-I/home/alanlord/bin/arduino-1.6.12/hardware/esp8266com/esp8266/libraries/ESP8266WiFi/src" "-I/home/alanlord/bin/arduino-1.6.12/hardware/esp8266com/esp8266/libraries/ESP8266HTTPClient/src" "/tmp/arduino_build_96324/sketch/freq-counter.ino.ino.cpp" -o "/tmp/arduino_build_96324/sketch/freq-counter.ino.ino.cpp.o"
/home/alanlord/Personal/Projects/polytunnel-sensing-project/esp-code/arduino/zentris/freq-counter.ino/freq-counter.ino.ino: In function 'void saveData2ThingsSpeak()':
freq-counter.ino:571: error: 'sensors' was not declared in this scope
   for (unsigned int sensor=0; sensor < sizeof(sensors)/sizeof(struct mySensor); sensor++) {
                                               ^
/home/alanlord/Personal/Projects/polytunnel-sensing-project/esp-code/arduino/zentris/freq-counter.ino/freq-counter.ino.ino: In function 'void setup()':
freq-counter.ino:699: error: 'sensors' was not declared in this scope
   for (unsigned int i=0; i < sizeof(sensors)/sizeof(struct mySensor); i++) {
                                     ^
/home/alanlord/Personal/Projects/polytunnel-sensing-project/esp-code/arduino/zentris/freq-counter.ino/freq-counter.ino.ino: In function 'void loop()':
freq-counter.ino:733: error: 'sensors' was not declared in this scope
   for (unsigned int sensor=0; sensor < sizeof(sensors)/sizeof(struct mySensor); sensor++) {

**Comment by Zentris** [comment]
Hello,
i'm very sorry, you found an error :-(

An interims solution:
Please add into the privates.h file the following lines:

// ---------------------------------------------
// my sensor GPIO definition (must be adapt on your own hardeware configuration !
// ---------------------------------------------
// struct mySensor {unsigned int sensorId; unsigned int intGPIO; unsigned int powerGPIO; unsigned long soilMoistAveraged;};
// ---------------------------------------------
mySensor sensors[] { (mySensor) { 1, 12, 14, 0 }  // Birkenfeige (Ficus benjamina)
                    ,(mySensor) { 2,  5,  4, 0 }  // Einblatt (Spathiphyllum)
                   };

and edit these for your GPIOs and so on, see the comment for this structure..

I will correct this error in the next days... 

Very thanks and best regards,
Zentris

**Comment by theopensourcerer** [comment]
Thanks for the update. There is no need to apologise - I totally understand that problems happen in software :-) and C isn't my strong point. 

I will update my code and try again when I get a little free time.

Thanks again and have a good Christmas and New Year.

**Comment by Zentris** [comment]
corrected in Rev 2.2.0 pre

Thanks and also a happy new year :-) !!
